package com.ahmed.constat;

public enum Circumstances {
    EN_STATIONNEMENT,
    QUITTE_UN_STATIONNEMENT,
    PRENAINT_UN_STATIONNEMENT,
    SORTAIT_DU_PARKING,
    ENGAGEAIT_SUR_UNE_PLACE_A_SENS_GIRATOIRE,
    ROULAIT_SUR_UNE_PLACE_A_SENS_GIRATOIRE,
    HEURTAIT_DANS_LE_MEME_SENS_ET_SUR_FIL_DIFFERENTE,
    CHANGEAIT_DE_FIL,
    DOUBLAIT,
    VIRAIT_A_GAUCHE,
    VIRAIT_A_DROITE,
    RECULAIT,
    EMPIETAIT_SUR_UNE_VOIE_RESERVE_A_LA_CIRCULATION_EN_SENS_INVERSE,
    VENAIT_DE_DROIT_DANS_UN_CARREFOUR,
    ABSENCE_D_OBSERVATION_DU_SIGNIAL_DE_PRIORITE
}
